apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  PGHOST: cGdob3N0         # "pghost"
  PGUSER: cG9zdGdyZXM=     # "postgres"
  PGPASSWORD: MTIzNA==     # "1234"
  PGDATABASE: cG9zdGdyZXM= # "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z pghost 5432; do echo "waiting for postgres..."; sleep 2; done']
      containers:
      - name: myapp
        image: hkvge777/my-php-app
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: myapp-secret
